Here let's work on regression. Find a data set and build a KNN Regression and an OLS regression. Compare the two. How similar are they? Do they miss in different ways?

Create a Jupyter notebook with your models. At the end in a markdown cell write a few paragraphs to describe the models' behaviors and why you favor one model or the other. Try to determine whether there is a situation where you would change your mind, or whether one is unambiguously better than the other. Lastly, try to note what it is about the data that causes the better model to outperform the weaker model. Submit a link to your notebook below.



In [38]:
import numpy as np
import pandas as pd
import matplotlib.pylab as plt
import seaborn as sns
from sklearn import neighbors
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.model_selection import cross_val_score

In [2]:
# %load ../../utility/version_print.py
#record module versions used in cell 1
#
def version_recorder():
    '''
    only works if import is first cell run. prints and then returns dictionary with modules:version.
    '''
    import pkg_resources
    resources = In[1].splitlines()
    ##ADD: drop lines if not _from_ or _import_
    version_dict = { resource.split()[1].split(".")[0] : pkg_resources.get_distribution(resource.split()[1].split(".")[0]).version for resource in resources }
    return version_dict
version_recorder()

{'numpy': '1.16.4',
 'pandas': '0.25.0',
 'matplotlib': '3.1.1',
 'seaborn': '0.9.0',
 'sklearn': '0.0'}

In [3]:
pwd

'C:\\Users\\User\\Documents\\GitHub\\thinkful_notes\\Unit_2_supervised_learning\\20'

In [6]:
df = pd.read_csv("../../data_sets/ramen-ratings.csv", )
df.head()

Review #           Brand  \
0      2580       New Touch   
1      2579        Just Way   
2      2578          Nissin   
3      2577         Wei Lih   
4      2576  Ching's Secret   

                                             Variety Style Country Stars  \
0                          T's Restaurant Tantanmen    Cup   Japan  3.75   
1  Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...  Pack  Taiwan     1   
2                      Cup Noodles Chicken Vegetable   Cup     USA  2.25   
3                      GGE Ramen Snack Tomato Flavor  Pack  Taiwan  2.75   
4                                    Singapore Curry  Pack   India  3.75   

  Top Ten  
0     NaN  
1     NaN  
2     NaN  
3     NaN  
4     NaN

In [7]:
df.nunique()

Review #    2580
Brand        355
Variety     2413
Style          7
Country       38
Stars         51
Top Ten       38
dtype: int64

In [8]:
#only include if brand is commonly tested
brand_list = (df.Brand.value_counts() > 10).index
df = df[df["Brand"].isin(brand_list)]

In [9]:
#top ten would be separate target
df.drop(columns="Top Ten", inplace=True)


In [10]:
df.dropna(how='any', inplace=True)

In [11]:
df = df[df.Stars.str.isdigit()]
y = df.Stars

In [12]:
X = pd.get_dummies(df[["Style", "Country", "Brand"]], drop_first=True)
X.head()

Style_Bowl  Style_Box  Style_Cup  Style_Pack  Style_Tray  \
1            0          0          0           1           0   
6            0          0          1           0           0   
10           0          0          0           1           0   
11           0          0          0           1           0   
14           0          0          0           1           0   

    Country_Bangladesh  Country_Brazil  Country_Cambodia  Country_Canada  \
1                    0               0                 0               0   
6                    0               0                 0               0   
10                   0               0                 0               0   
11                   0               0                 0               0   
14                   0               0                 0               0   

    Country_China  ...  Brand_Wei Chuan  Brand_Wei Lih  Brand_Western Family  \
1               0  ...                0              0                     0   
6               0  ...                0              0                     0   
10              0  ...                0              0                     0   
11              0  ...                0              0                     0   
14              0  ...                0              0                     0   

    Brand_World O' Noodle  Brand_Wu Mu  Brand_Wu-Mu  Brand_Wugudaochang  \
1                       0            0            0                   0   
6                       0            0            0                   0   
10                      0            0            0                   0   
11                      0            0            0                   0   
14                      0            0            0                   0   

    Brand_Xiao Ban Mian  Brand_Yamachan  Brand_Yum Yum  
1                     0               0              0  
6                     0               0              0  
10                    0               0              0  
11                    0               1              0  
14                    0               0              0  

[5 rows x 282 columns]

In [14]:
X.columns[X.dtypes != "uint8"]

Index([], dtype='object')

In [20]:
for col in X.columns:
    print(X[col].dtype)

uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint8
uint

In [30]:
y = pd.to_numeric(y)

In [32]:
regression_model = LinearRegression()
regression_model.fit(X, y)
print("rsquare is {}".format(regression_model.score(X, y)))

rsquare is 0.5745301123670111


In [37]:
cross_val_score(regression_model, X, y, cv=5)

array([-8.58703432e+26, -1.23371894e+27, -3.89074400e+25, -2.37203386e+26,
       -1.32174091e+26])

Very poor CV. will try another Regression model.

In [39]:
ridge_model = Ridge()
ridge_model.fit(X, y)
print("rsquare is {}".format(ridge_model.score(X, y)))

rsquare is 0.5106085635454151


In [40]:
cross_val_score(ridge_model, X, y, cv=5)

array([ 0.01804503,  0.14490214,  0.12029419,  0.0828164 , -0.27015293])

Still poor. Highly categorical data may be poor fit for this model type.

In [31]:
knn_model = neighbors.KNeighborsRegressor(n_neighbors=2)
knn_model.fit(X, y)
print("rsquared is {}".format(knn_model.score(X, y)))

rsquared is 0.461693812021445


In [41]:
cross_val_score(knn_model, X, y, cv=5)

array([-0.78304577, -0.21570234,  0.01037006, -0.01967306, -0.58637207])

In [34]:
knn_model2 = neighbors.KNeighborsRegressor(n_neighbors=10, weights='distance')
knn_model2.fit(X, y)
print("rsquared is {}".format(knn_model2.score(X, y)))

rsquared is 0.6625044221755905


In [42]:
cross_val_score(knn_model2, X, y, cv=5)

array([-0.18861091,  0.01602315,  0.12318203,  0.02487342, -0.47738882])